### ISSUE TITLE
Install script is noisy about errors, which seem to not be true errors but polling results

### ISSUE THREAD

**Issue by barecode** [kabanero-io/kabanero-foundation#110]
This happens repeatedly... I'm assuming its polling for status as it exits successfully eventually... it just looks bad and I would  strongly recommend we supress the error or reword it because my first thought was "oh crap what did I break?"
```
+ oc get crd services.serving.knative.dev
No resources found.
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "services.serving.knative.dev" not found
+ sleep 1
```

I think this output as-is is very confusing (as I said, I initially thought I made a mistake somewhere). I would strongly recommend an alternative would be to print a message that says something to the effect of "Waiting for Knative services to be available..." or something to that effect.

**Comment by stevenschader** [comment]
Also there could a an infinite loop using these constructs:
# Need to wait for knative serving CRDs before installing tekton webhook extension
until oc get crd services.serving.knative.dev
do
  sleep $SLEEP_SHORT
done

Seems my CRC env lost it's auth during the processing and it's just plain stuck looping.....
[kevin@svtcrc-16749-1 ocp42]$ oc get crd services.serving.knative.dev
error: You must be logged in to the server (Unauthorized)
[kevin@svtcrc-16749-1 ocp42]$ echo $?
1

**Comment by dacleyra** [comment]
The script is re-written for 0.3.0
set -x is still in effect
Infinite loop checks still exist
Install script can be run multiple times without negative consequence

https://github.com/kabanero-io/kabanero-operator/releases/download/0.3.0-rc.1/install.sh

Note this issue with OLM can delay the install process while it waits for the catalog source to be ready
https://github.com/operator-framework/operator-lifecycle-manager/issues/1098
